### ISSUE TITLE
Short-circuit Evaluations Causing Problems

### ISSUE THREAD

**Issue by ehulders** [meraki/provisioning-lib#10]
In the updateswitchport function of  merakiapi in the 3.5 module, some condition statements which check for boolean values are short circuiting (as they should), but this is preventing a value of True from being pushed to the switch port.

As an example:
    if enabled and (enabled is not False or not True):
        raise ValueError("Enabled must be a boolean variable")
    elif enabled:
        putdata['enabled'] = str(enabled)

If enabled is True, then "if enabled" is true, and then "enabled is not False", which is also true, the condition statement stops there not evaluating against "not True" and we raise a ValueError.  Consider a simplified way to write this:

    if not isinstance(enabled, bool):
        raise ValueError("Enabled must be a boolean variable")
    else:
        putdata['enabled'] = str(enabled)

PoE, isolation, and rstp in updateswitchport have the same problem.  
Also, line 2309 should be "putdata['isolationEnabled'] = str(isolation)"

**Comment by ghost** [comment]
Excellent catch!  Thanks for the feedback, will clean up the update switch port function on next commit.
