### ISSUE TITLE
API

### ISSUE THREAD

**Issue by bigbydesign** [meraki/provisioning-lib#3]
Rob,

I believe there is a disconnect between Meraki Support and Sales representatives knowing about this API. We have over 2000 Meraki APs. I have went through all channels to trying to find this functionality. I do note one key piece of functionality in which I have submitted to the wishlist, contacted support, and told my sales representative is very important functionality we don't currently have. We need an API function to reboot an AP, for a multitude of reasons. I can elaborate this more, however I do not want to do that in this public forum. 

I would really appreciate a contact.

https://my.ncocc-k12.org/staffdir/emailme.asp?userid=1

Thanks,

Andy

**Comment by opencolin** [comment]
Hi Andy,

Thanks for asking a question on GitHub. I'm happy to answer any and all questions - and my email is below. 

The API documentation is available on http://developers.meraki.com and if you register you get an email directly from me.  I would suggest asking support for help on the issue with your Cisco Meraki gear as support might have an alternative solution. I'll look through the wishlist for your feature requests like the Reboot AP via API.

Note that the free open source code on our GitHub such as this provisioning library are provided for free - and require coding skills. I recommend the developers website and the community forum for questions about the sample code or scripting: http://developers.meraki.com/community 

By the way, Rob is hard at work on updating this code - probably in the next week or so. 

Regards,
Colin Lowenberg
developers@meraki.com

**Comment by robertcsapo** [comment]
You could disable the port (or turn off PoE) on Meraki switches, which is connecting to the Meraki AP.

#### HTTP REQUEST
```PUT /devices/[serial]/switchPorts/[number]```

#### PARAMETERS
- ```name``` The name of the switch port
- ```tags``` The tags of the switch port
- ```enabled``` The status of the switch port
- ```type``` The type of the switch port ("access" or "trunk")
- ```vlan``` The VLAN of the switch port
- ```voiceVlan``` The voice VLAN of the switch port. Only applicable to access ports.
- ```allowedVlans``` The VLANs allowed on the switch port. Only applicable to trunk ports.
- ```poeEnabled``` The PoE status of the switch port
- ```isolationEnabled``` The isolation status of the switch port
- ```rstpEnabled``` The rapid spanning tree protocol status
- ```stpGuard``` The state of the STP guard ("disabled", "root guard", "BPDU guard")
- ```accessPolicyNumber``` The number of the access policy of the switch port. Only applicable to access ports.

**Comment by bigbydesign** [comment]
Not using Meraki switch, so that doesn't help my situation.

**Comment by weggy75** [comment]
Hi,

Did you end up using the sample-templatebind-retainvlans.py script? 

Do you know if there is a way to be selective about which networks are migrated?

**Comment by ghost** [comment]
Hi @weggy75 you can alter line 25 of the script to include any qualifiers you would like.  As it is currently written `    if network['type'] == 'appliance' and network['name'][:2] == 'zz':` limits the networks that the script runs on to networks that are appliance based and have 'zz' as the first two characters of the name.

The easiest way you could select networks would be to use network tags: https://documentation.meraki.com/zGeneral_Administration/Inventory_and_Devices/Organization_Overview#Network_Tags

Then match based on that tag by altering line 25 to look something like this:
`    if network['type'] == 'appliance' and tagname in network['tags']:` where tagname is the tag you applied to the networks that you want to migrate.  You'll want to test in a lab environment to make sure you have the intended outcome. 

Thanks

**Comment by weggy75** [comment]
Hi merakiwatt, Thanks for the prompt reply. I will let you know how the testing goes.

**Comment by weggy75** [comment]
Hi merakiwatt,

My first attempt was using;

if network['type'] == 'appliance' and tagname in network['tags']: where tagname == 'MIGRATE':

and it returned message;

 SyntaxError: invalid syntax @ ==


My second attempt was using;

if network['type'] == 'appliance' and network['tags'] == 'MIGRATE':

and it returned message;

Templates Operation Successful - See returned data for results

Network Operation Successful - See returned data for results
 
Unfortunately the networks tagged with MIGRATE did not bind.   

Any idea what failed?

Thanks.

Weggy75

**Comment by ghost** [comment]
@weggy75 the tags are returned with spaces surrounding them as shown in the Dashboard API docs which wouldn't match your second attempt as.  Your best bet would be to use the original syntax, tagname in the original example was a place holder for your actual tag name that you would like to match on.

Your code should look similar to this:

`if network['type'] == 'appliance' and 'MIGRATE' in network['tags']:`

**Comment by weggy75** [comment]
Turns out the whitespace was my problem.  Thanks very much for your time and help merakiwatt!!

**Comment by weggy75** [comment]
Hi merakiwatt,

May I please have more of your time?  I updated the sample-templatebind-retainvlans.py script to include fixedIpAssignments and reservedIpRanges  :  


![add_1](https://user-images.githubusercontent.com/29579036/27487975-5f0a72d0-5803-11e7-952d-08fde170f98e.jpg)


I also updated merakiapi.py :  

![add_2](https://user-images.githubusercontent.com/29579036/27488143-ff5f2208-5803-11e7-8f4a-089633c3f7b7.jpg)


The updated script returned "HTTP 500 - Server Error" for the VLAN update.      

![error](https://user-images.githubusercontent.com/29579036/27488215-3eceb854-5804-11e7-993d-7fdc1cfcd2f5.jpg)



Any thoughts on what went wrong?   Is there a better approach for retaining fixedIpAssignments and reservedIpRanges VLAN data?


Thanks for your time.

**Comment by shiyuechengineer** [comment]
Hi weggy75,
 
Taking a look at this, I think you’re running into an error here because the variables are being formatted into strings.
 
However, in the [example PUT call](https://dashboard.meraki.com/api_docs#update-a-vlan) in the documentation for updating VLANs, fixedIpAssignments is a dict and reservedIpRanges is a list.
 
I think because those two variables are being inputted as strings, Dashboard returns back the 500 error. I'm actually in the process of updating the library with the latest calls as well as individual calls' functionality (that may have been added since). Stay tuned here shortly!

**Comment by bigbydesign** [comment]
I was just wondering if there is going to be any updates done to the API to allow a method for rebooting an AP? I posted this same request about 10 months ago and just wondered if it is any closer to becoming a reality?

**Comment by opencolin** [comment]
Meraki / Support generally advise not to reboot APs. If there is an issue that requires a reboot, it’s possibly a bug. Please call or email support.

However I had to solve this exact problem for a customer and managed to reboot thousands of APs using an API script to remove and add the AP from the network. This forces the AP to reboot and connect to the Meraki Cloud to get it's config. 

Slow Method - I have tested and used this with customers.
Step 1. Remove AP from Network
Step 2. Confirm the AP is now removed - it will have a default config.
Step 3. Add AP to Network
Step 4. Confirm the AP is now online with the original config.

You may be able to speed this up a bit by using the upstream switch to detect when the AP reboots and add it back before it gets the default config.
Fast Method - Confirmed this works:
Step 1. Remove AP from Network
Step 2. Monitor the port to detect when the AP reboots.
Step 3. Add AP to Network.
Step 4. Confirm the AP is now online with the original config.
