### ISSUE TITLE
Merakiapi and vars file

### ISSUE THREAD

**Issue by jleatham** [meraki/provisioning-lib#5]
Not sure where to put feature requests.  

It took a minute or two of digging to realize that you need to create a vars.py file (with org and apikey variables), AND that you need to manually change the base_url variable in the merakiapi.py to fit your dashboard URL.  Why not move that base_url to the vars.py file, and then make it more clear in the documentation that you need to modify it there.  That way there is only one file you are making changes to.  Also put a dummy vars.py file in the repository so that it is more clear that you need to have it and what the required variables are.

**Comment by ghost** [comment]
Hi @jleatham the base_url variable should work as defined in the py script with Dashboard redirecting the API call to the correct shard for the organization.  In testing, the requests module that this script relies on handles the redirects without issue.  Is there a particular call that you needed to change the base_url for?

Good catch on the vars.py file, I'll throw up a sample, currently only the VPN hub migration sample script leverages the vars.py file.

**Comment by jleatham** [comment]
Just checked, you are correct, no need to change base URL.  I just assumed because I had to do that when I was using curl to make API calls.  So,disregard that part.  Thanks.
