### ISSUE TITLE
enable vlans on MX

### ISSUE THREAD

**Issue by jleatham** [meraki/provisioning-lib#6]
I don't see in the list of functions in merakiapi.py where you can enable VLANs on an MX.   I tested creating a network, and adding/updating MXIP and vlan IPs once vlans were enabled on the network MX .  But once you create the network, you have to manually go into the dashboard, enable vlans, and then go back to your script to make any changes.  Am I missing something?

**Comment by ghost** [comment]
Hi @jleatham you are correct, currently there is no API call available to enable VLANs on an MX network.  It's a great suggestion though!  What customers have done in the past is to leverage configuration templates with VLAN's enabled and "unique" address assignment.  You can then use the API call to override the VLAN IP assignment even though the network is bound to a template.
